### ISSUE TITLE
Documentation and File permission

### ISSUE THREAD

**Issue by devran01** [ARMmbed/mbed-example-network#27]
1. apache-2.0.txt has execute permission for all users including root.
2. helloworld-udpclient --> README.md --> Using Debugger:  Step 5 refers to Step 10 of Getting started. It should be Step 9.
3.  Similar issue with helloworld-tcpclient --> README.md.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-872

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-998
