### ISSUE TITLE
UDP time example does not get UTC time on windows

### ISSUE THREAD

**Issue by ErkkiMehtala** [ARMmbed/mbed-example-network#32]
I got example compiled and loaded, when reseting it prints:

{{start}}
UDP client IP Address is 192.168.100.21
Starting DNS Query for utcnist.colorado.edu

missing expected print like:
UDP: 3635245075 seconds since 01/01/1900 00:00 GMT

I have windows7 and working over VPN. 
utcnist.colorado.edu is pinging OK.

**Comment by ErkkiMehtala** [comment]
I had maybe wrong baud speed in putty. Now it works.

{{start}}
{{start}}
UDP client IP Address is 192.168.100.21
Starting DNS Query for utcnist.colorado.edu
DNS Response Received:
utcnist.colorado.edu = 128.138.140.44
Sending "time" to 128.138.140.44:37
Data Available!
UDP: 3654499447 seconds since 01/01/1900 00:00 GMT
{{success}}
{{end}}

**Comment by bogdanm** [comment]
That's not it. If you had the wrong baud, you'd have gotten a weird output all over the place, not a few correct lines and then silence. @bremoran has a potential fix for this.

**Comment by bremoran** [comment]
This looks like a DNS query was lost to me.  It is probably a failure in LwIP's DNS implementation.  I don't think there's a straight-forward fix for this.

**Comment by ErkkiMehtala** [comment]
Ok. Maybe I used first right speed, then wrong one because it was completely silent. Then right speed and it just worked fine with full prints. So maybe this original error is occasional (?).
