### ISSUE TITLE
dhcp fails, stuck at {{start}}

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/mbed-example-network#36]
my network seems to be fine, with dhcp seemingly functioning properly with my pc.  however, the examples get stuck after timing out trying to get an ip address through dhcp.  No error or debug information reported to the terminal.  Just stuck after the {{start}} prints out.

110	    if (use_dhcp) {
111	        dhcp_start(&netif);
112	
113	        // Wait for an IP Address
114	        // -1: error, 0: timeout
115	        while (if_up == 0);

target platform: frdm-k64f

same behavior with:
mbed-example-network-test-helloworld-udpclient
mbed-example-network-test-helloworld-tcpclient

terminal output:
{{start}}

build version tagged: mbedos-techcon-oob1

**Comment by simonqhughes** [comment]
ARM Internal Ref: IOTSFW-1073

**Comment by maclobdell** [comment]
after further investigation, this looks like a network router issue.  however, the real problem is that there is no timeout and no error status reporting when dhcp fails.

**Comment by bremoran** [comment]
@maclobdell There is an existing issue reported for ignoring timeouts: https://github.com/ARMmbed/sal-iface-eth/issues/2  I have opened a pull request to fix this: https://github.com/ARMmbed/sal-iface-eth/pull/9

**Comment by bremoran** [comment]
I believe this is fixed.
