### ISSUE TITLE
error: [Errno 98] Address already in use complaining comes when starting GDB debug

### ISSUE THREAD

**Issue by ernotormikoski** [ARMmbed/mbed-example-network#39]
After error I pressed enter and could be debug as normal. Here is log about starting debugger.

info: found mbed-example-network-test-helloworld-udpclient at test/mbed-example-network-test-helloworld-udpclient
info: preparing PyOCD gdbserver...
info: finding connected board...
info: new board id detected: 02400201AA3A4E5957C4B3E1
info: board allows 5 concurrent packets
info: DAP SWD MODE initialised
info: IDCODE: 0x2BA01477
info: K64F not in secure state
info: 6 hardware breakpoints, 4 literal comparators
info: CPU core is Cortex-M4
info: FPU present
info: 4 hardware watchpoints
info: starting PyOCD gdbserver...
info: Telnet: server started on port 4444
info: GDB server started at port:3333
GNU gdb (GNU Tools for ARM Embedded Processors) 7.8.0.20150604-cvs
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-unknown-linux-gnu --target=arm-none-eabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from test/mbed-example-network-test-helloworld-udpclient...done.
info: One client connected!
mbed_enter_sleep (obj=<optimized out>) at /home/erntor01/workspace/outofbox/mbed-example-network/yotta_modules/mbed-hal-ksdk-mcu/source/sleep.c:51
51	}
(gdb) Exception in thread semihost-telnet:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyOCD/target/semihost.py", line 327, in _server
    self.connected = self._abstract_socket.connect()
  File "/usr/local/lib/python2.7/dist-packages/pyOCD/gdbserver/gdb_socket.py", line 36, in connect
    self.init()
  File "/usr/local/lib/python2.7/dist-packages/pyOCD/gdbserver/gdb_socket.py", line 31, in init
    self.s.bind(('', self.port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

(gdb) load

**Comment by 0xc0170** [comment]
You already reported this to another example today - ARMmbed/example-mbedos-blinky. I referenced there a valinor issue which is a tracking issue for this bug. This is a duplicate, therefore we can close this.
