### ISSUE TITLE
[Error 98] created by errno while using GDB

### ISSUE THREAD

**Issue by hasnainvirk** [ARMmbed/mbed-example-network#40]
Setup: Linux, GCC, ArmCC
helloworld applications while running with GDB. GDB works fine. However, it shows the following Error.

 * Error 98 , Address already in use. This issue has been reported before. However not fixed yet.

Detaching from program: /home/hasnain/Desktop/OOB2/mbed-example-network/build/frdm-k64f-gcc/test/mbed-example-network-test-helloworld-udpclient, Remote target
info: Client detached
Ending remote debugging.
project files have been generated in: test
hasnain@ubuntu:~/Desktop/OOB2/mbed-example-network$ ps ux | grep gdb
hasnain   7966  0.0  0.0  18928   936 pts/3    S+   08:00   0:00 grep --color=auto gdb
hasnain@ubuntu:~/Desktop/OOB2/mbed-example-network$ ps aux | grep gdb
hasnain   7968  0.0  0.0  18928   936 pts/3    S+   08:01   0:00 grep --color=auto gdb
hasnain@ubuntu:~/Desktop/OOB2/mbed-example-network$ sudo yt debug mbed-example-network-test-helloworld-udpclient
info: found mbed-example-network-test-helloworld-udpclient at test/mbed-example-network-test-helloworld-udpclient
info: preparing PyOCD gdbserver...
info: finding connected board...
info: new board id detected: 02400225c36f4e730000000000000000000000003eb5b3cb
info: board allows 5 concurrent packets
info: DAP SWD MODE initialised
info: IDCODE: 0x2BA01477
info: K64F not in secure state
info: 6 hardware breakpoints, 4 literal comparators
info: CPU core is Cortex-M4
info: FPU present
info: 4 hardware watchpoints
info: starting PyOCD gdbserver...
info: Telnet: server started on port 4444
info: GDB server started at port:3333
GNU gdb (GNU Tools for ARM Embedded Processors) 7.8.0.20150604-cvs
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-unknown-linux-gnu --target=arm-none-eabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from test/mbed-example-network-test-helloworld-udpclient...done.
info: One client connected!
mbed_enter_sleep (obj=<optimized out>)
    at /home/hasnain/Desktop/OOB2/mbed-example-network/yotta_modules/mbed-hal-ksdk-mcu/source/sleep.c:51
51	}
(gdb) Exception in thread semihost-telnet:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyOCD/target/semihost.py", line 327, in _server
    self.connected = self._abstract_socket.connect()
  File "/usr/local/lib/python2.7/dist-packages/pyOCD/gdbserver/gdb_socket.py", line 36, in connect
    self.init()
  File "/usr/local/lib/python2.7/dist-packages/pyOCD/gdbserver/gdb_socket.py", line 31, in init
    self.s.bind(('', self.port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

**Comment by 0xc0170** [comment]
Thanks for reporting. This is however not related to this example. You can test any other to get this pyOCD. I'll close this issue.

btw, there's a fix: https://github.com/mbedmicro/pyOCD/pull/205
